services:
  snaparser_server:
    image: vanillaiice/snaparser_server
    command: ["--http", "--log"]
    ports:
      - "8888:8888"
    restart: unless-stopped

  snaparser_webui_server:
    image: vanillaiice/snaparser_webui_server
    depends_on:
      - snaparser_server
    ports:
      - "7788:7788"
    volumes:
      - caddy_data:/data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

volumes:
  caddy_data:
